server:
  port: 9230
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: true
    #表示是否注册自身到eureka服务器， 做集群是设置成true 生产配置为true
    registerWithEureka: false
    #表示是否从eureka服务器获得注册信息，生产配置为true
    fetchRegistry: false
    #默认为30s 生产使用缺省时间，测试环境修改小点
    registry-fetch-interval-seconds: 15
    #心跳时间，生产使用缺省时间，即服务续约间隔时间（缺省为30秒，生产使用缺省时间，测试环境修改小点）
    service-url: http://localhost:9230
    registry-server-connect-timeout-seconds: 5

spring:
  devtools:
    enabled: true
  application:
    #应用名称，别名
    name: config-client
  profiles:
    active: @profiles.active@
  cloud:
    config:
      discovery:
        enabled: false
        service-id: config-server
      name: ${Spring.application.name}
      profile: ${Spring.profiles.active}
      server:
        git:
          uri: D:\GitLog
          search-paths: D:\GitLog
          default-label: develog